### ISSUE TITLE
Running Live Csound in Atom w Hydra?

### ISSUE THREAD

**Issue by micah-frank-studio** [kunstmusik/csound-live-code#17]
Hi Steven,

I would really like to get Csound Live running in Atom so that I can send osc messages to Hydra and have everything in the same environment.

I have the ide extension for Csound installed in Atom. Is there a way to get Live Csound up and running too?

**Comment by kunstmusik** [comment]
I don't see any live coding features from the csound-ide extension.  @nwhetsell can you clarify if there is, or if there are plans to add any?  

If there's a way to do that, then all you would need is this repo checked out and you could start csound in a terminal with the livecode.csd and send messages from Atom to it.

**Comment by nwhetsell** [comment]
There is no explicit support for live Csound coding in [ide-csound](https://github.com/nwhetsell/ide-csound), and unfortunately I have no plans to add this.

**Comment by kunstmusik** [comment]
Thanks Nate for the clarification. A separate extension for it would be the way forward then.  I haven't been using Atom and am short on time at the moment, but I can look at Nate's extensions as a model and try to put something together.

**Comment by micah-frank-studio** [comment]
Ok. Thanks for the info. In the meantime I will just send osc to hydra and work with what I’ve got.

**Comment by micah-frank-studio** [comment]
Sorry for all the questions. I would really love to be able to use this in my configuration. It says in the README.md

> > The library may be used:
> 
> by #including the livecode.orc file in your own project,

and in intro.md

> This library is used with desktop Csound installations as well as used as part of the http://live.csound.com web application.

How exactly can I use it outside of the web app? Doesn't some mechanism need to be in place to evaluate sections and handle the callbacks?

**Comment by kunstmusik** [comment]
Check out livecode.csd.  I use this on the desktop when live coding from
vim.  It starts up csound in UDP server mode with --port=10000.  From
csound-repl (my vim plugin), it will send UDP messages to csound using port
10000.  There's information about Csound's UDP server mode here:

https://csound.com/docs/manual/udpserver.html

and the kinds of messages you can send.  From any editor, you use need to
be able to send a UDP message with text.  (I got as far as looking at dgram
for node and Atom but haven't had a chance to look further unfortunately.)

Let me know if you have any other questions!

**Comment by micah-frank-studio** [comment]
OK, thank you! I will investigate...

**Comment by micah-frank-studio** [comment]
I'm up and running with python3 enabled vim and csound. I was able to get a sound going with a normal .csd 

I also have csound-repl plugin installed. 

I opened livecode.csd with the following
```
<CsoundSynthesizer>
<CsOptions>
--port=10000 -o dac -m0
</CsOptions>
<CsInstruments>

sr	= 48000	
ksmps	=	64
nchnls	=	2
0dbfs	=	1

#include "livecode.orc"

schedule("Sub1", 0, 2, 440, 0.5)

</CsInstruments>
</CsoundSynthesizer>
```

I tried to evaluate the 'schedule' line with ctrl+enter and command+enter in both normal and visual mode but nothing happens. Is there a different key combo or am I perhaps missing a step?

Thanks

**Comment by kunstmusik** [comment]
Yes, it's <leader>eo to evaluate orchestra code and <leader>es to evaluate
score code.  (can use :help csound-repl  to view the manual).  I have
<leader> mapped to , in my .vimrc file, but should be backslash by default.

**Comment by micah-frank-studio** [comment]
Ah silly me. You have to keep the .csd with the port assignment running the entire session and then code in a separate window. I got it working now! Thanks Steven. Now I just have to brush up on my vim chops.

**Comment by micah-frank-studio** [comment]
I managed to get this working (work-arounding ;) by sending OSC to Hydra in Atom. Not a horrible workaround and allows me to keep the vim csound code window floating above the visuals in atom. Working on a more refined UDO for that so I can simply include the op message in the event schedule message.
