### ISSUE TITLE
Some info on temporal recursion?

### ISSUE THREAD

**Issue by micah-frank-studio** [kunstmusik/csound-live-code#18]
Would it be possible to get a little more info on temporal recursion? From what I understand p1 is used within the instrument as a callback for either next_measure() or next_beat() - or I guess whatever time you want?

So does simply including 
`schedule(p1, next_beat())`
within the instrument definition repeat it at next_beat() rate?

I have the following but I think I'm still missing something.

```
instr Add
        asig = oscili(0.25, p4)
        asig2 = oscili(0.25, p4*2)
        asig += asig2
        asig *= expon(1,p3,0.001)
        out(asig, asig) 
endin

instr Arp
schedule("Add", 0, 2, 110)
schedule("Add", 0.4, 2, 100)
schedule("Add", 0.6, 0.6, 110)
schedule("Add", 0.9, 1, 100)
schedule (p1, next_measure, 1)
endin

schedule("Arp", 0, 1)
```

**Comment by kunstmusik** [comment]
Yes, that's all correct. For your last example to work, I had modify it to have the parenthesis next to the function call name and also use next_measure(), like so:

```
instr Arp
schedule("Add", 0, 2, 110)
schedule("Add", 0.4, 2, 100)
schedule("Add", 0.6, 0.6, 110)
schedule("Add", 0.9, 1, 100)
schedule(p1, next_measure(), 1)
endin
```

If you're going to use livecode.orc's clock, you'll also have to be mindful that within Arp, the time units you probably want to use are beats, like so:

```
instr Arp
schedule("Add", 0, 2, 110)
schedule("Add", beats(1), 2, 100)
schedule("Add", beats(2), 0.6, 110)
schedule("Add", beats(2.25), 0.6, 110)
schedule("Add", beats(2.5), 0.6, 110)
schedule("Add", beats(2.75), 0.6, 110)  
schedule("Add", beats(3), 1, 100)
schedule(p1, next_measure(), 1)
endin
```

with that, you can change tempo with ```set_tempo(108)``` and everything will remain in sync. 

For an example of temporal recursion with cslc there's this video:

https://www.youtube.com/watch?v=F2yMD8szSoU&t=343s

**Comment by micah-frank-studio** [comment]
Thanks - that's working. I'm officially live coding in Csound now!

**Comment by kunstmusik** [comment]
Fantastic, enjoy!
