### ISSUE TITLE
Stopping instruments / Reevaluating

### ISSUE THREAD

**Issue by micah-frank-studio** [kunstmusik/csound-live-code#20]
Hi Steven,

I'm trying to stop instruments that are getting recursions and/or reevaluate instruments after changing a p field but it is not working so well for me.

'stop('instr')' actually triggers another instance
and 
'clear_instr' seems to render the instrument blank so I cannot use it again until I reload the file.

I see in the livecode.orc that each time 'start()' is run it checks to see if the instrument is running and then turns it off before reactivating. But for me it it only adds another instance.

Do you have any tips there? Or any examples you could point me to? 

```
instr grv
schedule("grain",0,4,"bowbounce.aif",2.9,1.3)
endin
start("grv")
clear_instr("grain")
```

```
gi1 ftgen 1,0,8192,20,2,1

instr grain
Sfname=p4
kamp=0.5
kfreq=10
kpitch=p5
kgrsize=0.2
kprate=p6
iolaps=3
	agrainL, agrainR diskgrain Sfname, kamp, kfreq, kpitch, kgrsize, kprate, gi1, iolaps
outs agrainL, agrainR
schedule(p1, next_measure(),1,Sfname,p5,p6)
endin

```

**Comment by kunstmusik** [comment]
Yes, start/stop/kill are for always-on instruments. I use it for a different kind of live coding than with temporal recursion so probably not the right tool here.  The thing about temporal recursion is that it uses the event scheduler and there is generally going to be at least one item on the scheduler waiting to be fired.  I don't think there is a way to remove pending events from Csound's scheduler. 

So to end the recursion, you can either:

1. comment out the body of the instrument and re-evaluate (or use clear_instr)
2. comment out the recursion call (the schedule p1) 

The former is good if you want to end all future calls, the latter is good in the moment as it doesn't take much time to use ctrl-; to comment out the line then re-evaluate the instrument.

To reuse the instrument, you can wait until after the recursion ends. So if I did #2 above, it might look like: 

1. Find instrument to end recursion
2. comment out recursive schedule 
3. eval instrument with <leader>eo
4. uncomment out recursive schedule (probably would use u to undo)
5. 3. eval instrument with <leader>eo
6. later, re-eval schedule call outside of instrument to restart the process

I think if you setup your performance to have the initial schedule and clear_instr lines already around, you could use those to start/stop the process and just have to remember to eval the instrument again before starting.

**Comment by micah-frank-studio** [comment]
Thanks. I got that working now.
