### ISSUE TITLE
Using Macros in the live code?

### ISSUE THREAD

**Issue by micah-frank-studio** [kunstmusik/csound-live-code#21]
Can `schedule` be used with Macros somehow?
I am trying to create some shortcuts like 

`#define SOUND  #"test",0,1,"bowbounce.aif",1,1#`
 this is in the #INCLUDE file. And I am trying to access it with this in the live code file.
`schedule($SOUND)
`
Macros work as expected if they are accessed within the #INCLUDE files. However, Csound is throwing a syntactical error on the '$' if it's evaluated in the live code. Do I need to use an escape character or something?

**Comment by kunstmusik** [comment]
I don't really use macros myself, but I think the issue you're running into
is that Csound does not keep macro definitions around between compilations
and are only valid for the single eval.  (I filed an issue about this some
time ago: https://github.com/csound/csound/issues/896).
